### ISSUE TITLE
Implement reflection function

### ISSUE THREAD

**Issue by slifin** [lisachenko/z-engine#15]
https://www.php.net/manual/en/class.reflectionfunction.php

Maybe it'll be possible to do lisp style repl driven development if we could redefine functions at runtime (assuming all other calls get redirected to the new revision of the function automatically)

**Comment by lisachenko** [comment]
Hello!
As you can see, `ReflectionFunction` is already implemented in the source code (available at https://github.com/lisachenko/z-engine/blob/master/src/Reflection/ReflectionFunction.php).

This means that you can do some basic operation with functions, but `PHP` has two different internal structures for user-defined functions and internal function, thus implementation is partial. For example, you can not redefine an internal-function at the current moment, as it requires a little bit more work.

**Comment by slifin** [comment]
ah nice I should have checked the source
