### ISSUE TITLE
Custom keywords

### ISSUE THREAD

**Issue by aolko** [lisachenko/z-engine#17]
Hi there, is it possible to (re)define keywords?

**Comment by lisachenko** [comment]
Hello!
What do you mean by redefining keywords? :)

**Comment by lisachenko** [comment]
It should be possible to redefine opcodes somewhen, but I haven’t plans to implement this ASAP, because it is very dangerous.

**Comment by aolko** [comment]
let's say i want real `module`s, in order to do that i need to implement `module` keyword as well as some macro, is it possible with your package?

**Comment by lisachenko** [comment]
@aolko see my previous comment. It should be doable via `zend_compile_file` and `zend_compile_string` hooks, but this question is out of my current scope of investigation, because there are too many things to implement and make this library stable.

**Comment by lisachenko** [comment]
It is possible now to control the AST tree of original source code during compilation, so you could check for token with specific meaning and adjust tree if required.

**Comment by aolko** [comment]
how would i detect a usual construct (in normal languages):
`module "AModule"` or `import "AModule"`
and transform it into the usual php mess of namespace and includes?
