### ISSUE TITLE
Dead code detection?

### ISSUE THREAD

**Issue by garex** [lisachenko/z-engine#35]
Is it possible to use this lib for dead-code detection? If it is, then it will be good to state it in README.
Or provide some example.

**Comment by lisachenko** [comment]
@garex I think it is impossible to detect dead-code with this tool or I don't know how to do it right now. I know about phan, it uses `ast` extension to work with PHP native structures. With this library you could access AST information and analyze it somehow to detect dead-code. But it is very complex task...

**Comment by garex** [comment]
1. Add aspect to all methods in some dir.
2. When code goes inside it mark once somehow, that method X is alive somewhere.
3. After some time, gather info about live methods from somewhere, gather info about all methods (statically). Diff it and you will see walking deads.

**Comment by lisachenko** [comment]
Ok, I see now what you want. In theory, this should be doable, but in practice there will be a lot of pain to do that.
Therefore I can start with method hooks. Because current implementation can only replace existing method or function with closure. And AOP requires an ability to call original code (but how?).

**Comment by garex** [comment]
I dunno ))
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


ср, 12 февр. 2020 г. в 17:21, Alexander Lisachenko <notifications@github.com

**Comment by lisachenko** [comment]
This is question for me to solve :) I’ll comment here when method hooks will be available.

**Comment by dzentota** [comment]
Maybe you can find answer here https://github.com/krakjoe/tombs

**Comment by garex** [comment]
> Maybe you can find answer here https://github.com/krakjoe/tombs

We already was there )) https://github.com/krakjoe/tombs/graphs/contributors
