### ISSUE TITLE
[FAQ] Licensing

### ISSUE THREAD

**Issue by lisachenko** [lisachenko/z-engine#36]
This issue clarifies the usage of this library with other projects and describes terms of usage.

- This library, provided under **RPL** license can be used **for free** for any open-source projects without any limitations **while source code of these projects or libraries is also open-sourced**.
- For open-source libraries that are distributed under more permissive license types like **MIT** and **GPL** you could obtain a **free** persistent premium license for your open-source project either **by contributing to this project itself** (I accept PR with tests, documentation and new features, bug fixes are not counted) or by applying the [treeware license](https://treeware.earth/) to your project. Your project should also mention explicitly that it is powered by the [`Z-Engine`](https://github.com/lisachenko/z-engine) in your readme file.
- For commercial use, please contact me via email **lisachenko.it at gmail.com**. For small companies (up to 10 developers) it will cost about **$100/year only** which can be compared to the price of PHP developer **per one hour**. This should be acceptable price of speeding up your development or using extra powerful extensions built on top of `Z-Engine` library.

I'm going to spend most of received money on charity (mostly related to climate programs) and supporting other open-source projects.

You could quickly find projects that are built on top of the `Z-Engine` by clicking the ![изображение](https://user-images.githubusercontent.com/640114/74348031-1b49bc00-4dc3-11ea-9139-3223007bca24.png) button at the top.

**Comment by avierr** [comment]
> price of PHP developer per one hour

I get paid 300USD/Month, 
that's +- 1.5 USD/Hour

**Comment by lisachenko** [comment]
Migrated to the MIT license. Open-Source all the things 😃
