### ISSUE TITLE
Enable FFI+Opcache preload optimization

### ISSUE THREAD

**Issue by lisachenko** [lisachenko/z-engine#8]
Loading/parsing definition of C headers in runtime is not good, also, `ffi.enable` is equal to `preload` by default, thus, to make this library active by default, preloading of C headers should be added.

Ideally, this requires some infrastructure support to activate FFI preloading. 
 - [ ] Wait for integration of preloading into composer https://github.com/composer/composer/issues/7777
 - [x] Add cache-warming script that loads definition of headers during preload stage and compiles all library classes to be available by default to reduce class-loading time and compilation.
 - [x] Check long-running scripts (FPM, Standalone server) to ensure that there are no memory leaks and segfaults
 - [x] Wait for PHP7.4.2 to have a bug fix for: https://bugs.php.net/bug.php?id=78918
 - [ ] For Windows platform, preloading is not available anymore since 7.4.2 https://github.com/php/php-src/pull/4999

**Comment by lisachenko** [comment]
Opcache preloading is broken, need at least PHP7.4.2 to include a bug fix for https://bugs.php.net/bug.php?id=78918

**Comment by lisachenko** [comment]
Windows doesn't support opcache preloading as of 7.4.2.  Support was removed by @nikic in https://github.com/php/php-src/commit/59c3ddab13b5cc38e9406538801be8e134626793 due to ASLR restrictions for internal classes.

Additional details can be found here: https://github.com/php/php-src/pull/4999

**Comment by nikic** [comment]
Note that you can use `ffi.preload` instead. It works on Windows.

**Comment by lisachenko** [comment]
> Note that you can use `ffi.preload` instead. It works on Windows.

Thank you for replying, Nikita! I know about this configuration option, but my header file contains some macros which should be resolved in runtime accordind to platfrom, for example `ZEND_FASTCALL`, thus `ffi.preload` can't be used for this library.
